/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAirdropInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addUserAmount"
      | "airdropStarted"
      | "allowDaoFund"
      | "claim"
      | "daoFundAllowed"
      | "setTraitToken"
      | "startAirdrop"
      | "subUserAmount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addUserAmount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "airdropStarted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowDaoFund",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoFundAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTraitToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startAirdrop",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subUserAmount",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addUserAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropStarted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowDaoFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoFundAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTraitToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subUserAmount",
    data: BytesLike
  ): Result;
}

export interface IAirdrop extends BaseContract {
  connect(runner?: ContractRunner | null): IAirdrop;
  waitForDeployment(): Promise<this>;

  interface: IAirdropInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addUserAmount: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  airdropStarted: TypedContractMethod<[], [boolean], "view">;

  allowDaoFund: TypedContractMethod<[], [void], "nonpayable">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  daoFundAllowed: TypedContractMethod<[], [boolean], "view">;

  setTraitToken: TypedContractMethod<
    [_traitToken: AddressLike],
    [void],
    "nonpayable"
  >;

  startAirdrop: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  subUserAmount: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addUserAmount"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "airdropStarted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "allowDaoFund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "daoFundAllowed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setTraitToken"
  ): TypedContractMethod<[_traitToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startAirdrop"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subUserAmount"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
