/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EntityTrading } from "./EntityTrading";
export type { IEntityTrading } from "./IEntityTrading";
