/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EntityTrading__factory } from "./EntityTrading__factory";
export { IEntityTrading__factory } from "./IEntityTrading__factory";
