/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EntityForging } from "./EntityForging";
export type { IEntityForging } from "./IEntityForging";
