/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITraitForgeNft__factory } from "./ITraitForgeNft__factory";
export { TraitForgeNft__factory } from "./TraitForgeNft__factory";
