/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITraitForgeNft } from "./ITraitForgeNft";
export type { TraitForgeNft } from "./TraitForgeNft";
