/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EntityForging__factory } from "./EntityForging__factory";
export { IEntityForging__factory } from "./IEntityForging__factory";
