/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DevFund__factory } from "./DevFund__factory";
export { IDevFund__factory } from "./IDevFund__factory";
