/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iUniswapV2RouterSol from "./IUniswapV2Router.sol";
export type { iUniswapV2RouterSol };
export type { DAOFund } from "./DAOFund";
export type { IDAOFund } from "./IDAOFund";
