/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EntropyGenerator } from "./EntropyGenerator";
export type { IEntropyGenerator } from "./IEntropyGenerator";
